### ISSUE TITLE
EDA Playground Link

### ISSUE THREAD

**Issue by gupta409** [gupta409/Processor-UVM-Verification#3]
It would be nice to have a ready to run version of the project in EDA Playground. This would require loading the code and setting up the project in EDA Playground. Finally making it ready compile and run.

**Comment by rpjayaraman** [comment]
Hi @gupta409, Just made the code working in EDA playground. Link: https://www.edaplayground.com/x/aevr
I have reduced the iterative count inside processor_sequence to 100 inorder to run in EDA. 
i found scoreboard failure in MOV and LOAD instruction, is it a known issue ? or else i can dig into it !! 

Let me know

**Comment by gupta409** [comment]
Hi @rpjayaraman 
My apologies for the late response.
Thank you for helping setup this project on EDA Playground. I'm sure it should help people getting up to speed with the project. I have update the project README with your link. 

> i found scoreboard failure in MOV and LOAD instruction, is it a known issue ? or else i can dig into it !!
I'm not aware of this issue. Please create a new issue if you'd like and feel free to dig in for a fix if you'd like.

Thanks!
