### ISSUE TITLE
Some questions about makefile

### ISSUE THREAD

**Issue by Zhoulinfeng0510** [gupta409/Processor-UVM-Verification#4]
Hello, I am currently learning the relevant knowledge of UVM, and hope to get more familiar with VUVM through this project of yours. I saw that the makefile you uploaded was compiled through VCS. I hope to be able to compile through questa sim. In this case, what kind of makefile modification is required? Looking forward to your reply!

**Comment by gupta409** [comment]
Hi @Zhoulinfeng0510,
You can use the following reference to make a Makefile for questa sim.
https://github.com/VerificationExcellence/UVMReference/blob/master/apb_project/Makefile.questa

**Comment by Zhoulinfeng0510** [comment]
thank you very much!
